name: cv_generator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  uv-generator:
    name: Generate CV
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./script/cv
        
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: uv run ..\..\script\cv\cv_generator.py