name: cv_generator

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  uv-generator:
    name: Generate CV
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./script/cv

    steps:
      - uses: actions/checkout@v4
      
      - name: Install git
        run: |
          sudo apt-get update
          sudo apt-get install git -y

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Set git
        run: |
              git config user.name "GitHub Actions Bot"
              git config user.email "<>"
              cd $GITHUB_WORKSPACE
              git fetch 

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: uv run cv_generator.py -o cv_generator

      - name: Commit
        run: |
          git add .
          git commit -m 'Generated CV PDF'
          git push

      - name: Teardown when the workflow failed
        if: failure() && steps.build_step.outcome == 'failure'
        run: |
          git stash -u